CREATE DATABASE EmploymentDB
GO
USE EmploymentDB
GO

CREATE TABLE USERS
(
	userId INT IDENTITY(1000,1)PRIMARY KEY,
	userName VARCHAR(50) NOT NULL,
	userPass VARCHAR(50) NOT NULL,
	name VARCHAR(100),
	lastName VARCHAR(100),
	cv VARBINARY(MAX),
	cvName VARCHAR(MAX),
	rol VARCHAR(3) NOT NULL,
	career VARCHAR(500),
	contact VARCHAR(10) NULL     
)

CREATE TABLE JOB
(
	jobId INT IDENTITY(1000,1) PRIMARY KEY,
	title VARCHAR(500) NOT NULL,
	descriptionJob NVARCHAR(MAX) NOT NULL,
	requirements VARCHAR(MAX) NOT NULL,
	dateStart DATE NOT NULL,
	companyName VARCHAR(500) NOT NULL,
	companyAdress VARCHAR(500) NOT NULL,
	schedule VARCHAR(100) NOT NULL,
	contractJob VARCHAR(100),
	modality VARCHAR(100),
	career VARCHAR(500) 

)

CREATE TABLE GRADUATEPLUS
(
	gradId INT IDENTITY(1000,1) PRIMARY KEY,
	name VARCHAR(300) NOT NULL,
	descriptionGrad NVARCHAR(MAX) NOT NULL,
	career VARCHAR(500) NOT NULL,
	photo VARBINARY(MAX)
)

CREATE TABLE MAILBOX
(
	mailId INT IDENTITY(1000,1) PRIMARY KEY,
	comment NVARCHAR(MAX) NOT NULL,
	userId int FOREIGN KEY (userId) REFERENCES USERS(userId)
)

CREATE TABLE APPLYJOB
(
	applyId INT IDENTITY(1000,1) PRIMARY KEY,
	userId int FOREIGN KEY (userId) REFERENCES USERS(userId),
	jobId int FOREIGN KEY (jobId) REFERENCES JOB(jobId)
)

CREATE TABLE CAREERS
(
	careerId INT PRIMARY KEY IDENTITY(1000,1),
	career VARCHAR(500),
	area VARCHAR(500)
)

GO
INSERT INTO CAREERS VALUES ('TECNICO SUPERIOR EN HIGIENE DENTAL', 'SALUD'),
						   ('TECNICO SUPERIOR EN MECANICA DENTAL', 'SALUD'),
						   ('TECNICO SUPERIOR EN IMAGENES MEDICAS', 'SALUD'),
						   ('TECNICO SUPERIOR EN ENFERMERIA', 'SALUD'),
						   ('TECNICO SUPERIOR EN GASTRONOMIA', 'TURISMO'),
						   ('TECNICO SUPERIOR EN SISTEMAS DE INFORMACION TURISTICA', 'TURISMO'),
						   ('TECNICO SUPERIOR EN GESTION DE ALOJAMIENTO TURISTICO', 'TURISMO'),
						   ('TECNICO SUPERIOR EN ALIMENTOS Y BEBIDAS', 'TURISMO'),
						   ('TECNICO SUPERIOR EN EMPRESAS DE INTERMEDIACION TURISTICA', 'TURISMO'),
						   ('TECNICO SUPERIOR EN PANADERIA Y REPOSTERIA', 'TURISMO'),
						   ('TECNICO SUPERIOR EN TECNOLOGIAS DE MANUFACTURA', 'INDUSTRIAL'),
						   ('TECNICO SUPERIOR EN LOGISTICA', 'INDUSTRIAL'),
						   ('TECNICO SUPERIOR EN DISEÑO DE MODAS', 'ARTE'),
						   ('TECNICO SUPERIOR EN DISEÑO GRAFICO', 'ARTE'),
						   ('TECNICO SUPERIOR EN DISEÑO DE INTERIORES', 'ARTE'),
						   ('TECNICO SUPERIOR EN INDUSTRIA DEL MUEBLE', 'ARTE'),
						   ('TECNICO SUPERIOR EN FOTOGRAFIA', 'ARTE'),
						   ('TECNICO SUPERIOR EN PRODUCION DE EVENTOS', 'ARTE'),
						   ('TECNICO SUPERIOR EN CONSTRUCCION', 'CONSTRUCCION'),
						   ('TECNICO SUPERIOR EN SOPORTE INFORMATICO', 'INFORMATICA'),
						   ('TECNICO SUPERIOR EN DESARROLLO DE SOFTWARE', 'INFORMATICA'),
						   ('TECNICO SUPERIOR EN ADMINISTRACION DE REDES', 'INFORMATICA'),
						   ('TECNICO SUPERIOR EN MECANICA AUTOMOTRIZ', 'ELECTROMECANICA'),
						   ('TECNICO SUPERIOR EN ELECTRONICA', 'ELECTROMECANICA'),
						   ('TECNICO SUPERIOR EN ELECTRICIDAD', 'ELECTROMECANICA'),
						   ('TECNICO SUPERIOR EN REFRIGERACION', 'ELECTROMECANICA');


