// <auto-generated />
namespace API_EMPLEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTableCareer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTableCareer));
        
        string IMigrationMetadata.Id
        {
            get { return "202103041809313_updateTableCareer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
